version: '3.1'

services:
  spr_mysql:
    image: mysql
    container_name: spr_mysql
    restart: always
    environment:
      MYSQL_DATABASE: sprdb
      MYSQL_USER: uspr
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    